config/routes.rb
Api::Application.routes.draw do
  
  resources :roles
  resources :lists do
    resources :items do
      member do
        put :set_status
      end
    end
    
    # Subscription routes
    member do
      post :add_subscriber
      delete :remove_subscriber
    end
  end

  # User and auth
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  
  resources :user_sessions
  resources :users

  root :to => "lists#index"
  
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :title, :description
  
  belongs_to :owner, :class_name => "User"
  has_many :items
  
  has_many :subscriptions
  has_many :subscribers, :through => :subscriptions, :source => :user
  
  validates_presence_of :title
  validates_presence_of :owner
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  load_and_authorize_resource
  
  def index
    @lists = current_user.lists
    
    respond_to do |format|
      format.html
      format.json { render :json => @lists }
      format.xml  { render :xml => @lists }
    end
  end

  def show
    @list = List.find(params[:id])
    
    respond_to do |format|
      format.html
      format.json { render :json => @list }
    end
  end

  def new
    @list = List.new
    
    respond_to do |format|
      format.html
      format.json { render :json => @list }
    end
  end

  def create
    @list = List.new(params[:list])
    
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, :notice => "Successfully created list." }
        format.json { render :json => @list, :status => :created, :location => @list }
      else
        format.html { render :action => 'new' }
        format.json { render :json => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @list = List.find(params[:id])
    
    respond_to do |format|
      format.html
      format.json { render :json => @list }
    end
  end

  def update
    @list = List.find(params[:id])
    
    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, :notice  => "Successfully updated list." }
        format.json { head :ok }
      else
        format.html { render :action => 'edit' }
        format.json { render :json => @list.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def add_subscriber
    @list = List.find(params[:id])
    @user = User.find(params[:user_id])
    
    @subscription = @list.subscriptions.create(:user => @user)
    
    respond_to do |format|
      if @subscription.valid?
        format.html { redirect_to @list, :notice => "Subscriber successfully added." }
        format.json { head :ok }
      else
        format.html { redirect_to @list, :error => "Subscriber could not be added." }
        format.json { render :json => @subscription.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def remove_subscriber
    @list = List.find(params[:id])
    @user = User.find(params[:user_id])
    
    s = Subscription.find_by_list_id_and_user_id(@list.id, @user.id)
    s.destroy
    
    respond_to do |format|
      format.html { redirect_to @list, :notice => "Subscriber successfully removed." }
      format.json { head :ok }
    end
  end
  
  def destroy
    @list = List.find(params[:id])
    @list.destroy
    
    respond_to do |format|
      format.html { redirect_to lists_url, :notice => "Successfully destroyed list." }
      format.json { head :ok }
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.haml
= semantic_form_for @list do |f|
  = f.error_messages
  
  = f.input :title
  = f.input :description
  = f.input :owner
  
  = f.commit_button

app/views/lists/edit.html.erb
<% title "Edit List" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @list %> |
  <%= link_to "View All", lists_path %>
</p>

app/views/lists/index.html.erb
<% title "Lists" %>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>User</th>
  </tr>
  <% for list in @lists %>
    <tr>
      <td><%= list.title %></td>
      <td><%= list.description %></td>
      <td><%= list.owner %></td>
      <td><%= link_to "Show", list %></td>
      <td><%= link_to "Edit", edit_list_path(list) %></td>
      <td><%= link_to "Destroy", list, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New List", new_list_path %></p>

app/views/lists/new.html.erb
<% title "New List" %>

<%= render 'form' %>

<p><%= link_to "Back to List", lists_path %></p>

app/views/lists/show.html.haml
- title @list.title

%p
  = @list.description
%p
  Owner:
  = @list.owner

%h3 Items
%ul
  - for item in @list.items.relevant
    %li
      = link_to item.title, [@list, item]

%h3 Subscribers
%ul
  - for user in @list.subscribers
    %li
      = link_to user, user

%p
  = link_to "Edit", edit_list_path(@list)
  = link_to "Destroy", @list, :confirm => 'Are you sure?', :method => :delete
  = link_to "View All", lists_path