config/routes.rb
Api::Application.routes.draw do
  
  resources :roles
  resources :lists do
    resources :items do
      member do
        put :set_status
      end
    end
    
    # Subscription routes
    member do
      post :add_subscriber
      delete :remove_subscriber
    end
  end

  # User and auth
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  
  resources :user_sessions
  resources :users

  root :to => "lists#index"
  
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  
  has_many :owned_lists, :class_name => "List", :foreign_key => "owner_id"
  has_many :subscriptions
  has_many :subscribed_lists, :through => :subscriptions, :source => :list
  
  def lists
    owned_lists + subscribed_lists
  end
  
  def to_s
    username
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  authorize_resource
  skip_authorization_check :only => [:new, :create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, :notice => "Thank you for signing up! You are now logged in." }
      else
        format.html { render :action => 'new' }
      end
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  = f.error_messages
  %p
    = f.label :username
    %br
    = f.text_field :username
  %p
    = f.label :email, "Email Address"
    %br
    = f.text_field :email
  %p
    = f.label :password
    %br
    = f.password_field :password
  %p
    = f.label :password_confirmation, "Confirm Password"
    %br
    = f.password_field :password_confirmation
  %p
    = f.submit (@user.new_record? ? "Sign up" : "Update")

app/views/users/edit.html.haml
- title "Sign up"

= render 'form'

app/views/users/new.html.haml
- title "Sign up"

%p== Already have an account? #{link_to "Log in", login_path}.

= render 'form'