config/routes.rb
Api::Application.routes.draw do
  
  resources :roles
  resources :lists do
    resources :items do
      member do
        put :set_status
      end
    end
    
    # Subscription routes
    member do
      post :add_subscriber
      delete :remove_subscriber
    end
  end

  # User and auth
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  
  resources :user_sessions
  resources :users

  root :to => "lists#index"
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :title
  
  validates_presence_of :title
  validates_uniqueness_of :title
  validates_format_of :title, :with => /^[a-z]+$/
  
  has_many :subscriptions
  
  def to_s
    title
  end
  
  def to_param
    title.downcase
  end
  
  def self.default
    Role.find_or_create_by_title("read")
  end
  
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @roles = Role.all
  end

  def show
    @role = Role.find_by_title(params[:id])
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(params[:role])
    if @role.save
      redirect_to @role, :notice => "Successfully created role."
    else
      render :action => 'new'
    end
  end

  def edit
    @role = Role.find_by_title(params[:id])
  end

  def update
    @role = Role.find_by_title(params[:id])
    if @role.update_attributes(params[:role])
      redirect_to @role, :notice  => "Successfully updated role."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @role = Role.find_by_title(params[:id])
    @role.destroy
    redirect_to roles_url, :notice => "Successfully destroyed role."
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for @role do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/roles/edit.html.erb
<% title "Edit Role" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @role %> |
  <%= link_to "View All", roles_path %>
</p>

app/views/roles/index.html.erb
<% title "Roles" %>

<table>
  <tr>
    <th>Title</th>
  </tr>
  <% for role in @roles %>
    <tr>
      <td><%= role.title %></td>
      <td><%= link_to "Show", role %></td>
      <td><%= link_to "Edit", edit_role_path(role) %></td>
      <td><%= link_to "Destroy", role, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Role", new_role_path %></p>

app/views/roles/new.html.erb
<% title "New Role" %>

<%= render 'form' %>

<p><%= link_to "Back to List", roles_path %></p>

app/views/roles/show.html.erb
<% title "Role" %>

<p>
  <strong>Title:</strong>
  <%= @role.title %>
</p>

<p>
  <%= link_to "Edit", edit_role_path(@role) %> |
  <%= link_to "Destroy", @role, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", roles_path %>
</p>