config/routes.rb
Api::Application.routes.draw do
  
  resources :roles
  resources :lists do
    resources :items do
      member do
        put :set_status
      end
    end
    
    # Subscription routes
    member do
      post :add_subscriber
      delete :remove_subscriber
    end
  end

  # User and auth
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  
  resources :user_sessions
  resources :users

  root :to => "lists#index"
  
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :title, :done_at
  
  belongs_to :list
  belongs_to :user
  
  validates_presence_of :title, :user, :list
  
  # Default to only unfinished items
  scope :pending, where("done_at IS NULL")
  scope :recently_done, lambda { where(["done_at >= ?", 5.days.ago]) }
  
  def self.relevant
    pending + recently_done
  end
  
  def done?
    not done_at.nil?
  end
  
  def done=(value)
    if value
      self.done_at = DateTime.now
    else
      self.done_at = nil
    end
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  authorize_resource
  
  before_filter :load_list
  
  def index
    @items = @list.items
    
    respond_to do |format|
      format.html
      format.json { render :json => @items }
    end
  end

  def show
    @item = Item.find(params[:id])
    
    respond_to do |format|
      format.html
      format.json { render :json => @item }
    end
  end

  def new
    @item = Item.new
    @item.list = @list
    
    respond_to do |format|
      format.html
      format.json { render :json => @item }
    end
  end

  def create
    @item = Item.new(params[:item])
    @item.list = @list
    
    respond_to do |format|
      if @item.save
        format.html { redirect_to list_item_url(@list, @item), :notice => "Successfully created item." }
        format.json { render :json => @item, :status => :created, :location => @item }
      else
        format.html { render :action => 'new' }
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  def set_status
    @item = Item.find(params[:id])
    value = ActiveRecord::ConnectionAdapters::Column.value_to_boolean(params[:done])
    @item.done = value
    @item.save
    
    respond_to do |format|
      format.html { redirect_to list_item_url(@list, @item) }
      format.json { head :ok }
    end
  end

  def edit
    @item = Item.find(params[:id])
    
    respond_to do |format|
      format.html
      format.json { render :json => @item }
    end
  end

  def update
    @item = Item.find(params[:id])
    
    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to [@list, @item], :notice  => "Successfully updated item." }
        format.json { head :ok }
      else
        format.html { render :action => 'edit' }
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    
    respond_to do |format|
      format.html { redirect_to @list, :notice => "Successfully destroyed item." }
      format.json { head :ok }
    end
  end
  
  private
  
    def load_list
      @list = List.find(params[:list_id])
    end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= semantic_form_for [@list, @item] do |f|
  = f.input :title
  = f.commit_button

app/views/items/edit.html.erb
<% title "Edit Item" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", [@list, @item] %> |
  <%= link_to "View All", list_items_path(@list) %>
</p>

app/views/items/index.html.erb
<% title "Items" %>

<table>
  <tr>
    <th>Title</th>
    <th>Done At</th>
    <th>User</th>
  </tr>
  <% for item in @items %>
    <tr>
      <td><%= item.title %></td>
      <td><%= item.done_at %></td>
      <td><%= item.user_id %></td>
      <td><%= link_to "Show", [@list, item] %></td>
      <td><%= link_to "Edit", edit_list_item_path(@list, item) %></td>
      <td><%= link_to "Destroy", [@list, item], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Item", new_list_item_path(@list) %></p>

app/views/items/new.html.erb
<% title "New Item" %>

<%= render 'form' %>

<p><%= link_to "Back to List", list_items_path(@list) %></p>

app/views/items/show.html.erb
<% title "Item" %>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>
<p>
  <strong>Done At:</strong>
  <%= @item.done_at %>
</p>
<p>
  <strong>Created by:</strong>
  <%= @item.user %>
</p>

<p>
  <%= link_to "Edit", edit_list_item_path(@list, @item) %> |
  <%= link_to "Destroy", [@list, @item], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", list_items_path(@list) %>
</p>